# Generated by Django 4.1.2 on 2022-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_userinfo_alter_product_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
