# Generated by Django 4.1.2 on 2022-12-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_paymentmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
