# Generated by Django 4.1.2 on 2022-12-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_userinfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
    ]
