# Generated by Django 4.1.2 on 2022-11-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='cake',
            new_name='product',
        ),
    ]
